name: issue-opened

on:
  issues:
    types: [opened]

jobs:
  debug:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Update APK')
    steps:
      - name: Close issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.update({
              ...context.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })

            github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: 'Close this!'
            });
