name: Test Github Checkout Repository

on:
  push:

jobs:
  get-repository-with-checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#3278BD'
          SLACK_CHANNEL: random
          SLACK_USERNAME: GITHUB_BOT
      - name: dump Github context
        run: echo ${{ github.event.repository.name }}
        shell: bash
