name: Test Github Checkout Repository

on:
  push:

jobs:
  get-repository-with-checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: dump Github context
        run: echo ${{ github.event.repository.name }}
        shell: bash
